### ISSUE TITLE
OpenCL version of CK-TensorFlow failed

### ISSUE THREAD

**Issue by gfursin** [ctuning/ck-tensorflow#1]
I added OpenCL wrapper for TensorFlow to CK and it compiles:

 $ ck pull repo:ck-tensorflow
 $ ck install package:lib-tensorflow-opencl

(Note that you need CodePlay's computecpp)
But then the basic benchmark doesnt' start:
 $ ck run program:tensorflow

Traceback (most recent call last):
  File "../alexnet_benchmark.py", line 43, in <module>
    import tensorflow as tf
  File "/home/fursin/CK-TOOLS/tensorflow-opencl-master-lib.opencl-8.0-linux-64/lib/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/fursin/CK-TOOLS/tensorflow-opencl-master-lib.opencl-8.0-linux-64/lib/tensorflow/python/__init__.py", line 60, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/fursin/CK-TOOLS/tensorflow-opencl-master-lib.opencl-8.0-linux-64/lib/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/fursin/CK-TOOLS/tensorflow-opencl-master-lib.opencl-8.0-linux-64/lib/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/home/fursin/CK-TOOLS/tensorflow-opencl-master-lib.opencl-8.0-linux-64/lib/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: /home/fursin/CK-TOOLS/tensorflow-opencl-master-lib.opencl-8.0-linux-64/lib/tensorflow/python/_pywrap_tensorflow.so: undefined symbol: _ZN2cl4sycl7program30create_program_for_kernel_implENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPKhiPPKcSt10shared_ptrINS0_6detail7contextEE

Any help is appreciated.

**Comment by psyhtest** [comment]
This recent blog post by the lead TF-SYCL developer may be useful: http://deep-beta.co.uk/setting-up-tensorflow-with-opencl-using-sycl/

**Comment by psyhtest** [comment]
This ticket is quite old and no longer relevant, so I will close it. However, it's still non-trivial to build TensorFlow with SYCL support (e.g. see https://github.com/codeplaysoftware/tensorflow/issues/7).
