### ISSUE TITLE
HTTPError: 404 Client Error: Not Found for tensorflow-1.12.0-cp37-cp37m-linux_x86_64.whl

### ISSUE THREAD

**Issue by lzqtim** [ctuning/ck-tensorflow#128]
I got an error while install tensorflow using ck.
python3 version: 3.7.3
ck version: 1.9.9

```
Successfully installed django easydict enum-compat image joblib numpy pillow protobuf pytz scipy setuptools six sqlparse

Conditionally cleaning up the 'enum34' package...

Usage:
  /usr/bin/python3.7 -m pip uninstall [options] <package> ...
  /usr/bin/python3.7 -m pip uninstall [options] -r <requirements file> ...

no such option: --system

Downloading and installing TensorFlow prebuilt binaries (https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.12.0-cp37-cp37m-linux_x86_64.whl) ...

Collecting tensorflow==1.12.0 from https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.12.0-cp37-cp37m-linux_x86_64.whl
/usr/share/python-wheels/urllib3-1.22-py2.py3-none-any.whl/urllib3/connectionpool.py:860: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/lib/python3/dist-packages/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/usr/lib/python3/dist-packages/pip/download.py", line 659, in unpack_http_url
    hashes)
  File "/usr/lib/python3/dist-packages/pip/download.py", line 855, in _download_http_url
    resp.raise_for_status()
  File "/usr/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
**pip._vendor.requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.12.0-cp37-cp37m-linux_x86_64.whl**
Error: installation failed!

   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   CK detected a PROBLEM in the third-party CK package:

   CK package:           lib-tensorflow-1.12.0-cpu
   CK repo:              ck-tensorflow
   CK repo URL:          https://github.com/ctuning/ck-tensorflow
   CK package URL:       https://github.com/ctuning/ck-tensorflow/tree/master/package/lib-tensorflow-1.12.0-cpu
   Issues URL:           https://github.com/ctuning/ck-tensorflow/issues
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   Please, submit the log to the authors of this external CK package at "https://github.com/ctuning/ck-tensorflow/issues" to collaboratively fix this problem!

CK error: [package] package installation failed!
```

**Comment by psyhtest** [comment]
@lzqtim I think the issue is that there's no prebuilt `*.whl` for Python 3.7.

When I try to install the same package on a machine with Python 3.6, the package fetches from https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.12.0-cp36-cp36m-linux_x86_64.whl 
```
Collecting tensorflow==1.12.0 from https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.12.0-cp36-cp36m-linux_x86_64.whl
  Downloading https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.12.0-cp36-cp36m-linux_x86_64.whl (83.1MB)
     |████████████████████████████████| 83.1MB 13.5MB/s
```

I have manually checked that I can fetch from all of the following:
- https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.12.0-cp36-cp36m-linux_x86_64.whl
- https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.12.0-cp35-cp35m-linux_x86_64.whl
- https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.12.0-cp34-cp34m-linux_x86_64.whl
- https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.12.0-cp33-cp33m-linux_x86_64.whl

**Comment by psyhtest** [comment]
Now, if I try to install the latest TensorFlow v1.14:
```
$ ck install package --tags=lib,tensorflow,v1.14,vcpu,vprebuilt
...
Collecting tensorflow==1.14.0 from https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.14.0-cp36-cp36m-linux_x86_64.whl
```
and then:
```
$ wget https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.14.0-cp37-cp37m-linux_x64_64.whl
```
so that fails too. Unfortunately, we don't have any control over what Google place in their repositories :).

So I think the only option for you is to downgrade your version of Python to e.g. 3.6, and detect it as follows:
```
$ ck detect soft:compiler.python --full_path=`which python3.6`
```
Please let me know if you have any further questions.

**Comment by psyhtest** [comment]
Closing due to lack of activity.

Just to note that:
```
$ wget https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.14.0-cp37-cp37m-linux_x64_64.whl
```
still fails.
