### ISSUE TITLE
building bazel failed on 

### ISSUE THREAD

**Issue by DVEfremov** [ctuning/ck-tensorflow#3]
**Steps to reproduce**
* Ubuntu 
* ck pull repo:ck-tensorflow
* ck install package:lib-tensorflow-cpu

**Actual result**
Got error 

```
*** Installation path used: /home/daniil/CK-TOOLS/tool-bazel-master-linux-64

-----------------------------------
Resolving software dependencies ...

*** Dependency 1 = java-compiler (Java compiler):

    Resolved. CK environment UID = 4bfb0ae868ccbb6e (detected version 1.8.0_101)
-----------------------------------

Cloning from 'https://github.com/bazelbuild/bazel.git' ...
fatal: destination path 'src' already exists and is not an empty directory.

Compiling bazel ...

Building bazel ...
/home/daniil/CK/ck-tensorflow/package/tool-bazel/install.sh: line 38: cd: output: No such file or directory
Error: building bazel failed!
CK error: [package] package installation failed!
```

**Expected result**

* Installation without errors

**Comment by gfursin** [comment]
Confirm - the same on my machine - something happened - will check!
Thanks!

**Comment by gfursin** [comment]
The Bazel version on GitHub changed and it is not possible to compile it directly (need some workaround), hence I added 0.4.1 binary for Linux. I committed changes, so it should work now. 

Please, update all repos:
$ ck pull all 

May I ask you then to check it again, please? 
Thanks!

**Comment by DVEfremov** [comment]
I've applied:
* $ ck pull all
* $ ck install package:lib-tensorflow-cpu

Process worked much longer longer but got another error:

```
Collecting setuptools (from protobuf==3.1.0->tensorflow==0.12.0rc0)
  Downloading setuptools-30.2.0-py2.py3-none-any.whl (472kB)
    100% |████████████████████████████████| 481kB 1.2MB/s 
Installing collected packages: six, funcsigs, pbr, mock, numpy, setuptools, protobuf, wheel, tensorflow
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 335, in run
    prefix=options.prefix_path,
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 732, in install
    **kwargs
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 837, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 1039, in move_wheel_files
    isolated=self.isolated,
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "/usr/lib/python2.7/dist-packages/pip/locations.py", line 153, in distutils_scheme
    i.finalize_options()
  File "/usr/lib/python2.7/distutils/command/install.py", line 289, in finalize_options
    raise DistutilsOptionError("can't combine user with prefix, "
DistutilsOptionError: can't combine user with prefix, exec_prefix/home, or install_(plat)base
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

Setting up environment for installed package ...
  (full path = /home/daniil/CK-TOOLS/tensorflow-master-linux-64/lib/tensorflow/__init__.py)

  Software entry found: lib.tensorflow (30db354f469bb178)
-----------------------------------
Resolving software dependencies ...

*** Dependency 1 = bazel (Bazel):

    Resolved. CK environment UID = 1c11847098ee91b5 (detected version 0.4.1)

*** Dependency 2 = python (Python):

    Resolved. CK environment UID = f81091479abf0c02 (detected version 2.7.12)

*** Dependency 3 = compiler.gcc (GCC compiler):

    Resolved. CK environment UID = ad97ec9254403a58 (detected version 5.4.0)
-----------------------------------
CK error: [package] software not found in a specified path (/home/daniil/CK-TOOLS/tensorflow-master-linux-64/lib/tensorflow/__init__.py)!

```

I've tried to `check __init__.py` :

```
$ cat /home/daniil/CK-TOOLS/tensorflow-master-linux-64/lib/tensorflow/__init__.py
cat: /home/daniil/CK-TOOLS/tensorflow-master-linux-64/lib/tensorflow/__init__.py: No such file or directory

$ pwd
/home/daniil/CK-TOOLS/tensorflow-master-linux-64
$ ls -l
total 8
drwxrwxr-x 2 daniil daniil 4096 Dec  8 12:37 pkg
drwxrwxr-x 7 daniil daniil 4096 Dec  8 12:21 src
```

**Comment by gfursin** [comment]
This is a problem not with CK, but with Tensorflow deps and pip. Can you please try to run 
$ sudo pip install --upgrade pip
and then reinstall package, please?

**Comment by gfursin** [comment]
However, please do ck pull all, since I added check for errors during pip installation in tensorflow ...

**Comment by DVEfremov** [comment]
Now it works. I've applied just as you've said:
* $ ck pull all
* $ sudo pip install --upgrade pip
* $ ck install package:lib-tensorflow-cpu
And installation completed successfully:
`Environment entry added (487924a924ee01f5)!
Installation time: 1026.24897003 sec.
`

**Comment by gfursin** [comment]
BTW, did you manage to run

 $ ck run program:tensorflow-classification
and 
 $ ck run program:tensorflow
 $ ck run program:tensorflow --env.BATCH_SIZE=10 --env.NUM_BATCHES=5

Thanks!

**Comment by DVEfremov** [comment]
I've started crowdbech
$ ck crowdbench tensorflow --user=daniil.efremov@xored.com
--env.BATCH_SIZE=128 --env.NUM_BATCHES=100 --local

and i still has been  working looke like with out issue
and sure I've checked

$ ck run program:tensorflow-classification
$ ck run program:tensorflow
$ ck run program:tensorflow --env.BATCH_SIZE=10 --env.NUM_BATCHES=5

works fine as well.

2016-12-08 16:26 GMT+07:00 Grigori Fursin <notifications@github.com>:

**Comment by gfursin** [comment]
Cool! Thanks! I close this issue then!
