### ISSUE TITLE
benchmark-googlenet fails

### ISSUE THREAD

**Issue by psyhtest** [ctuning/ck-tensorflow#4]
Running `program:tensorflow` and selecting `benchmark-googlenet` results in:
```
executing code ...
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
    run_benchmark()
  File "/home/anton/CK_REPOS/ck-tensorflow/dataset/benchmark-googlenet/benchmark-googlenet.py", line 224, in run_benchmark
    last_layer = inference(images)
  File "/home/anton/CK_REPOS/ck-tensorflow/dataset/benchmark-googlenet/benchmark-googlenet.py", line 154, in inference
    incept3a = _inception(pool3,    192, 64, 96, 128, 16, 32, 3, 32)
  File "/home/anton/CK_REPOS/ck-tensorflow/dataset/benchmark-googlenet/benchmark-googlenet.py", line 131, in _inception
    incept = tf.concat(channel_dim, [conv1, conv3, conv5, pool])
  File "/home/anton/CK_TOOLS/tensorflow-prebuilt-cuda-1.0.0-compiler.cuda-8.0.61-lib.cudnn-api-5.1.5-linux-64/lib/tensorflow/python/ops/array_ops.py", line 1047, in concat
    dtype=dtypes.int32).get_shape(
  File "/home/anton/CK_TOOLS/tensorflow-prebuilt-cuda-1.0.0-compiler.cuda-8.0.61-lib.cudnn-api-5.1.5-linux-64/lib/tensorflow/python/framework/ops.py", line 651, in convert_to_tensor
    as_ref=False)
  File "/home/anton/CK_TOOLS/tensorflow-prebuilt-cuda-1.0.0-compiler.cuda-8.0.61-lib.cudnn-api-5.1.5-linux-64/lib/tensorflow/python/framework/ops.py", line 716, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/anton/CK_TOOLS/tensorflow-prebuilt-cuda-1.0.0-compiler.cuda-8.0.61-lib.cudnn-api-5.1.5-linux-64/lib/tensorflow/python/framework/constant_op.py", line 176, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/anton/CK_TOOLS/tensorflow-prebuilt-cuda-1.0.0-compiler.cuda-8.0.61-lib.cudnn-api-5.1.5-linux-64/lib/tensorflow/python/framework/constant_op.py", line 165, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/home/anton/CK_TOOLS/tensorflow-prebuilt-cuda-1.0.0-compiler.cuda-8.0.61-lib.cudnn-api-5.1.5-linux-64/lib/tensorflow/python/framework/tensor_    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/home/anton/CK_TOOLS/tensorflow-prebuilt-cuda-1.0.0-compiler.cuda-8.0.61-lib.cudnn-api-5.1.5-linux-64/lib/tensorflow/python/framework/tensor_util.py", line 367, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/home/anton/CK_TOOLS/tensorflow-prebuilt-cuda-1.0.0-compiler.cuda-8.0.61-lib.cudnn-api-5.1.5-linux-64/lib/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.
```

Tested with 3 freshly installed versions:
```
$ ck show env --tags=tensorflow
Env UID:         Target OS: Bits: Name:                               Version:       Tags:

4b0c4fb7a608c8cf   linux-64    64 TensorFlow library (prebuilt, cuda) 1.0.0          64bits,cuda,host-os-linux-64,lib,prebuilt,target-os-linux-64,tensorflow,tensorflow-cuda,v1,v1.0,v1.0.0
6dca1226a214393b   linux-64    64 TensorFlow library (prebuilt, cpu)  1.0.0          64bits,cpu,host-os-linux-64,lib,prebuilt,target-os-linux-64,tensorflow,tensorflow-cpu,v1,v1.0,v1.0.0
bdcf77dc8e5843fb   linux-64    64 TensorFlow library (cpu)            master-2e8cf80 64bits,host-os-linux-64,lib,target-os-linux-64,tensorflow,tensorflow-cpu,v0,v0.0
```

Full log: [googlenet.txt](https://github.com/ctuning/ck-tensorflow/files/827592/googlenet.txt)

**Comment by fanranGit** [comment]
@psyhtest, https://github.com/ctuning/ck-tensorflow/commit/561690043c06c82878ac1f108f7f5fb86cd2452e should help. This mistake appears due to arguments order change in bunch of functions somewhere in tensorflow 0.x.x.

**Comment by psyhtest** [comment]
@fanranGit Thanks! That error has gone but unfortunately I have further problems. 

I have updated the environments:
```
 ck show env --tags=lib,tensorflow
Env UID:         Target OS: Bits: Name:                               Version:       Tags:

6e7114c0890aafa7   linux-64    64 TensorFlow library (prebuilt, cuda) 1.0.1          64bits,cuda,host-os-linux-64,lib,prebuilt,target-os-linux-64,tensorflow,tensorflow-cuda,v1,v1.0,v1.0.1
df7a6bf9eb32d17b   linux-64    64 TensorFlow library (prebuilt, cpu)  1.0.1          64bits,host-os-linux-64,lib,target-os-linux-64,tensorflow,tensorflow-cpu,v1,v1.0,v1.0.1,vcpu,vprebuilt
bdcf77dc8e5843fb   linux-64    64 TensorFlow library (cpu)            master-2e8cf80 64bits,host-os-linux-64,lib,target-os-linux-64,tensorflow,tensorflow-cpu,v0,v0.0
```
The GPU version fails with:
```
Traceback (most recent call last):
  File "/home/anton/CK_REPOS/ck-tensorflow/dataset/benchmark-googlenet/benchmark-googlenet.py", line 8, in <module>
    import tensorflow.python.platform
  File "/home/anton/CK_TOOLS/tensorflow-prebuilt-cuda-1.0.1-lib.cudnn-api-5.1.5-linux-64/lib/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/anton/CK_TOOLS/tensorflow-prebuilt-cuda-1.0.1-lib.cudnn-api-5.1.5-linux-64/lib/tensorflow/python/__init__.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/anton/CK_TOOLS/tensorflow-prebuilt-cuda-1.0.1-lib.cudnn-api-5.1.5-linux-64/lib/tensorflow/python/__init__.py", line 61, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/anton/CK_TOOLS/tensorflow-prebuilt-cuda-1.0.1-lib.cudnn-api-5.1.5-linux-64/lib/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/home/anton/CK_TOOLS/tensorflow-prebuilt-cuda-1.0.1-lib.cudnn-api-5.1.5-linux-64/lib/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: libcudart.so.8.0: cannot open shared object file: No such file or directory

Failed to load the native TensorFlow runtime.
```

The CPU versions fail with:
```
E tensorflow/core/common_runtime/executor.cc:594] Executor failed to create kernel. Invalid argument: CPU BiasOp only supports NHWC.
         [[Node: conv1/BiasAdd = BiasAdd[T=DT_FLOAT, data_format="NCHW", _device="/job:localhost/replica:0/task:0/cpu:0"](conv1/Conv2D, conv1/biases/read)]]
Traceback (most recent call last):
  File "/home/anton/CK_REPOS/ck-tensorflow/dataset/benchmark-googlenet/benchmark-googlenet.py", line 264, in <module>
    tf.app.run()
  File "/home/anton/CK_TOOLS/tensorflow-prebuilt-1.0.1-linux-64/lib/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/anton/CK_REPOS/ck-tensorflow/dataset/benchmark-googlenet/benchmark-googlenet.py", line 260, in main
    run_benchmark()
  File "/home/anton/CK_REPOS/ck-tensorflow/dataset/benchmark-googlenet/benchmark-googlenet.py", line 245, in run_benchmark
    timing_entries.append(time_tensorflow_run(sess, last_layer, "Forward"))
  File "/home/anton/CK_REPOS/ck-tensorflow/dataset/benchmark-googlenet/benchmark-googlenet.py", line 182, in time_tensorflow_run
    _ = session.run(target_op)
  File "/home/anton/CK_TOOLS/tensorflow-prebuilt-1.0.1-linux-64/lib/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/home/anton/CK_TOOLS/tensorflow-prebuilt-1.0.1-linux-64/lib/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/home/anton/CK_TOOLS/tensorflow-prebuilt-1.0.1-linux-64/lib/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/home/anton/CK_TOOLS/tensorflow-prebuilt-1.0.1-linux-64/lib/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: CPU BiasOp only supports NHWC.
         [[Node: conv1/BiasAdd = BiasAdd[T=DT_FLOAT, data_format="NCHW", _device="/job:localhost/replica:0/task:0/cpu:0"](conv1/Conv2D, conv1/biases/read)]]

Caused by op u'conv1/BiasAdd', defined at:
  File "/home/anton/CK_REPOS/ck-tensorflow/dataset/benchmark-googlenet/benchmark-googlenet.py", line 264, in <module>
    tf.app.run()
  File "/home/anton/CK_TOOLS/tensorflow-prebuilt-1.0.1-linux-64/lib/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/anton/CK_REPOS/ck-tensorflow/dataset/benchmark-googlenet/benchmark-googlenet.py", line 260, in main
    run_benchmark()
  File "/home/anton/CK_REPOS/ck-tensorflow/dataset/benchmark-googlenet/benchmark-googlenet.py", line 224, in run_benchmark
    last_layer = inference(images)
  File "/home/anton/CK_REPOS/ck-tensorflow/dataset/benchmark-googlenet/benchmark-googlenet.py", line 148, in inference
    conv1 = _conv (images, 3, 64, 7, 7, 2, 2, 'SAME')
  File "/home/anton/CK_REPOS/ck-tensorflow/dataset/benchmark-googlenet/benchmark-googlenet.py", line 58, in _conv
    data_format=FLAGS.data_format),
  File "/home/anton/CK_TOOLS/tensorflow-prebuilt-1.0.1-linux-64/lib/tensorflow/python/ops/nn_ops.py", line 1316, in bias_add
    return gen_nn_ops._bias_add(value, bias, data_format=data_format, name=name)
  File "/home/anton/CK_TOOLS/tensorflow-prebuilt-1.0.1-linux-64/lib/tensorflow/python/ops/gen_nn_ops.py", line 281, in _bias_add
    data_format=data_format, name=name)
  File "/home/anton/CK_TOOLS/tensorflow-prebuilt-1.0.1-linux-64/lib/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/home/anton/CK_TOOLS/tensorflow-prebuilt-1.0.1-linux-64/lib/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/anton/CK_TOOLS/tensorflow-prebuilt-1.0.1-linux-64/lib/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): CPU BiasOp only supports NHWC.
         [[Node: conv1/BiasAdd = BiasAdd[T=DT_FLOAT, data_format="NCHW", _device="/job:localhost/replica:0/task:0/cpu:0"](conv1/Conv2D, conv1/biases/read)]]
```

I will look into the GPU failure. Any ideas about the CPU failure? (Clearly, "NHWC" != "NCHW".)

**Comment by psyhtest** [comment]
Funnily enough, when the GPU version fails, it suggest to go to a non-existent page:
```
See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#import_error
for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```
Care to report or fix?

**Comment by psyhtest** [comment]
The GPU failure can be resolved by running as follows:
```
$ ck run program:tensorflow \
  --env.LD_LIBRARY_PATH=/usr/local/cuda-8.0.61/lib64:/usr/local/cudnn-5.1/lib64
```
I will look into why the paths are not automatically resolved.

**Comment by psyhtest** [comment]
OK, I've done the following:
- Added `benchmark_cpu` and `benchmark_cuda` commands, which the user is now prompted to choose from.
- Added CUDA RT and cuDNN as dependencies for the `benchmark_cuda` command, so that it works fine even if these are installed in non-default locations.
- Added the `vcpu,vcuda` tags to `benchmark-alexnet`, and the `vcuda` tag to `benchmark-googlenet` and `benchmark-overfeat` (as they don't seem to be supported on the CPU). Now the user is not prompted to select a dataset for the `benchmark_cpu` command (as there's only one to choose from), but is presented with all the three benchmark datasets for the `benchmark_cuda` command.

Now everything seems to be working fine, so closing this ticket!
