### ISSUE TITLE
Prebuilt TensorFlow requires system protobuf

### ISSUE THREAD

**Issue by psyhtest** [ctuning/ck-tensorflow#84]
```
$ sudo python3 -m pip uninstall protobuf
$ ck install package:lib-tensorflow-1.10.1-cpu
$ ck run program:image-classification-tf-py
...
    * stderr.log

      Traceback (most recent call last):
        File "../classify.py", line 15, in <module>
          import tensorflow as tf
        File "/home/anton/CK_TOOLS/tensorflow-prebuilt-cpu-1.10.1-compiler.python-3.5.2-linux-64/lib/tensorflow/__init__.py", line 22, in <module>
          from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
        File "/home/anton/CK_TOOLS/tensorflow-prebuilt-cpu-1.10.1-compiler.python-3.5.2-linux-64/lib/tensorflow/python/__init__.py", line 52, in <module>
          from tensorflow.core.framework.graph_pb2 import *
        File "/home/anton/CK_TOOLS/tensorflow-prebuilt-cpu-1.10.1-compiler.python-3.5.2-linux-64/lib/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
          from google.protobuf import descriptor as _descriptor
      ImportError: No module named 'google.protobuf'
```

**Comment by psyhtest** [comment]
This depends on a particular TF version. For example, TF 1.13.1 requires `tensorflow-estimator` to be installed via `pip`. We now try and document such hidden dependencies, so closing.
